Repository AY2122S1-CS2103T-W13-4/tp, pull requests merged in 2021-11, with the labels that each got.

#199 Refactor link and unlink command
  src/main/java/seedu/address/logic/commands/friends/UnlinkFriendCommand.java
  src/main/java/seedu/address/model/FriendsList.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/friend/Friend.java
  src/main/java/seedu/address/model/friend/UniqueFriendsList.java
Labels: enhancement

#200 Fix bugs in UI based on PED
  build.gradle
  src/main/java/seedu/address/model/friend/Friend.java
  src/main/java/seedu/address/ui/FriendCard.java
  src/main/java/seedu/address/ui/FriendListPanel.java
  src/main/java/seedu/address/ui/GameCard.java
  src/main/java/seedu/address/ui/GameListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/FriendListCard.fxml
  src/main/resources/view/FriendListPanel.fxml
  src/main/resources/view/GameListCard.fxml
  src/main/resources/view/GameListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/model/friend/FriendTest.java
Labels: UI bug

#203 Update user guide and tests, Fix minor bugs
  docs/UserGuide.md
  docs/team/marcustxk.md
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/parser/MainParser.java
  src/main/java/seedu/address/logic/parser/friends/FriendCommandParser.java
  src/main/java/seedu/address/logic/parser/friends/ListFriendCommandParser.java
  src/main/java/seedu/address/logic/parser/games/GameCommandParser.java
  src/main/java/seedu/address/logic/parser/games/ListGameCommandParser.java
  src/main/java/seedu/address/model/friend/Day.java
  src/main/java/seedu/address/model/util/DayTimeUtil.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/parser/MainParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/friends/FriendCommandParserTest.java
  src/test/java/seedu/address/model/friend/DayTest.java
  src/test/java/seedu/address/model/util/DayTimeUtilTest.java
Labels: bug, documentation

#201 Fix UI bugs
  src/main/java/seedu/address/ui/FriendScheduleDayCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/FriendMainCardTable.fxml
  src/main/resources/view/FriendScheduleDayCard.fxml
  src/main/resources/view/FriendSchedulePanel.fxml
  src/main/resources/view/GameListPanel.fxml
  src/main/resources/view/GameMainCardTable.fxml
  src/main/resources/view/MainWindow.fxml
Labels: bug

#208 Fix UI issues
  src/main/java/seedu/address/ui/FriendSchedulePanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/FriendMainCardTable.fxml
  src/main/resources/view/FriendScheduleDayCard.fxml
  src/main/resources/view/FriendSchedulePanel.fxml
  src/main/resources/view/GameListCard.fxml
  src/main/resources/view/GameMainCardTable.fxml
  src/main/resources/view/MainWindow.fxml
Labels: bug

#217 Fix UI issues
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/FriendMainCardTable.fxml
  src/main/resources/view/FriendSchedulePanel.fxml
  src/main/resources/view/GameMainCardTable.fxml
  src/main/resources/view/MainWindow.fxml
Labels: bug

#209 Overhaul and update UG
  docs/UserGuide.md
  docs/images/ui-screenshots/friend-add.png
  docs/images/ui-screenshots/friend-delete.png
  docs/images/ui-screenshots/friend-edit.png
  docs/images/ui-screenshots/friend-get.png
  docs/images/ui-screenshots/friend-link.png
  docs/images/ui-screenshots/friend-list.png
  docs/images/ui-screenshots/friend-schedule.png
  docs/images/ui-screenshots/friend-skill-invalid-value.png
  docs/images/ui-screenshots/friend-skill-success.png
  docs/images/ui-screenshots/friend-unlink.png
  docs/images/ui-screenshots/game-add.png
  docs/images/ui-screenshots/game-delete.png
  docs/images/ui-screenshots/game-get.png
  docs/images/ui-screenshots/game-list.png
  docs/images/ui-screenshots/help.png
  docs/images/ui-screenshots/recommend.png
  docs/images/ui-screenshots/startup.png
  docs/images/ui-screenshots/ui-overview.png
  docs/images/ui-snapshots/friend-add.png
  docs/images/ui-snapshots/friend-delete.png
  docs/images/ui-snapshots/friend-edit.png
  docs/images/ui-snapshots/friend-get.png
  docs/images/ui-snapshots/friend-link.png
  docs/images/ui-snapshots/friend-list.png
  docs/images/ui-snapshots/friend-schedule.png
  docs/images/ui-snapshots/friend-skill-success.png
  docs/images/ui-snapshots/friend-unlink.png
  docs/images/ui-snapshots/game-add.png
  docs/images/ui-snapshots/game-get.png
  docs/images/ui-snapshots/game-list.png
  docs/images/ui-snapshots/help.png
  docs/images/ui-snapshots/startup.png
  docs/team/kevin9foong.md
  src/main/java/seedu/address/logic/commands/RecommendCommand.java
Labels: documentation

#218 Fix minor issues in UG
  docs/UserGuide.md
Labels: documentation

#214 Add Schedule feature implementation and Update PPP
  docs/DeveloperGuide.md
  docs/diagrams/ParserClasses.puml
  docs/diagrams/ScheduleSequenceDiagram1.puml
  docs/diagrams/ScheduleSequenceDiagram2.puml
  docs/images/ParserClasses.png
  docs/images/ScheduleSequenceDiagram1.png
  docs/images/ScheduleSequenceDiagram2.png
  docs/team/marcustxk.md
Labels: documentation

#229 Fix truncation and modify schedule list
  src/main/resources/view/FriendListCard.fxml
  src/main/resources/view/FriendMainCardTable.fxml
  src/main/resources/view/FriendSchedulePanel.fxml
  src/main/resources/view/GameListCard.fxml
  src/main/resources/view/GameMainCardTable.fxml
  src/main/resources/view/MainWindow.fxml
Labels: UI bug

#236 Fix developer guide bugs
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ScheduleSequenceDiagram1.puml
  docs/diagrams/ScheduleSequenceDiagram2.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/ScheduleSequenceDiagram1.png
  docs/images/ScheduleSequenceDiagram2.png
Labels: DG bug

#230 Add link feature implementation and update UI component in DG
  docs/DeveloperGuide.md
  docs/diagrams/LinkSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UiClassDiagramUiPart.puml
  docs/diagrams/UnlinkSequenceDiagram.puml
  docs/images/LinkSequenceDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UiClassDiagramUiPart.png
  docs/images/UnlinkSequenceDiagram.png
  docs/team/lzher385.md
  src/main/java/seedu/address/logic/commands/friends/UnlinkFriendCommand.java
  src/main/java/seedu/address/model/FriendsList.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/friend/UniqueFriendsList.java
  src/main/java/seedu/address/ui/FriendMainCardTable.java
Labels: documentation

#241 Fix minor UG bugs
  build.gradle
  docs/UserGuide.md
  docs/index.md
  src/main/java/seedu/address/model/ModelManager.java
Labels: documentation

#249 Add implementation detail for recommend
  docs/DeveloperGuide.md
  docs/diagrams/RecommendCommandActivityDiagram.puml
  docs/diagrams/RecommendCommandSequenceDiagram1.puml
  docs/diagrams/RecommendCommandSequenceDiagram2.puml
  docs/images/RecommendCommandActivityDiagram.png
  docs/images/RecommendCommandSequenceDiagram1.png
  docs/images/RecommendCommandSequenceDiagram2.png
  docs/team/kevin9foong.md
Labels: documentation

#246 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteGameSequenceDiagram.puml
  docs/diagrams/GetCommandWorkflowActivityDiagram.puml
  docs/diagrams/GetSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ScheduleSequenceDiagram2.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/DeleteGameSequenceDiagram.png
  docs/images/GetCommandWorkflowActivityDiagram.png
  docs/images/GetSequenceDiagram.png
  docs/images/LogicStorageDIP.png
  docs/images/ModelClassDiagram.png
  docs/images/ScheduleSequenceDiagram2.png
  docs/images/SeEduLogo.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
  docs/images/johndoe.png
  docs/images/request_access.png
  docs/img.png
  docs/team/yeluriketan.md
Labels: documentation

#256 Update RecommendCommand to show passing back of control to caller
  docs/DeveloperGuide.md
  docs/diagrams/RecommendCommandSequenceDiagram1.puml
  docs/images/RecommendCommandSequenceDiagram1.png
Labels: documentation

#259 Update UG screenshot description and DG headers to remove colon
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
  docs/team/kevin9foong.md
Labels: documentation

#255 Update testing section, add use cases, update formatting, remove all mentions of GAME_NAME
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteGameSequenceDiagram.puml
  docs/diagrams/DeleteGameSequenceDiagram2.puml
  docs/diagrams/ScheduleSequenceDiagram1.puml
  docs/diagrams/ScheduleSequenceDiagram2.puml
  docs/images/DeleteGameSequenceDiagram.png
  docs/images/DeleteGameSequenceDiagram2.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/ScheduleSequenceDiagram1.png
  docs/images/ScheduleSequenceDiagram2.png
Labels: DG bug

#262 Update DG use cases and Fix DG markdown bug
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/marcustxk.md
Labels: documentation, DG bug

#264 Update DG and PPP
  docs/DeveloperGuide.md
  docs/diagrams/LinkSequenceDiagram1.puml
  docs/diagrams/LinkSequenceDiagram2.puml
  docs/diagrams/UnlinkSequenceDiagram1.puml
  docs/diagrams/UnlinkSequenceDiagram2.puml
  docs/images/LinkSequenceDiagram.png
  docs/images/LinkSequenceDiagram1.png
  docs/images/LinkSequenceDiagram2.png
  docs/images/UnlinkSequenceDiagram.png
  docs/images/UnlinkSequenceDiagram1.png
  docs/images/UnlinkSequenceDiagram2.png
  docs/team/lzher385.md
Labels: documentation

#284 Update Model, 'get' in DG
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/GetSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram2.puml
  docs/diagrams/ModelClassDiagram3.puml
  docs/images/GetSequenceDiagram.png
  docs/images/ModelClassDiagram2.png
  docs/images/ModelClassDiagram3.png
  docs/team/yeluriketan.md
Labels: documentation

#289 Final update to PPP
  docs/team/yeluriketan.md
Labels: documentation

#290 Fix UG and DG bugs
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/marcustxk.md
Labels: documentation

#294 Fix formatting issues
  docs/UserGuide.md
Labels: documentation
