Repository AY2122S1-CS2103T-W13-4/tp, pull requests merged in 2021-10, with the labels that each got.

#58 Refactor codebase for new Game and GameFriendLink
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/LinkCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/FriendsList.java
  src/main/java/seedu/address/model/GamesList.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyGamesList.java
  src/main/java/seedu/address/model/friend/Friend.java
  src/main/java/seedu/address/model/friend/UniqueFriendsList.java
  src/main/java/seedu/address/model/friend/exceptions/FriendNotFoundException.java
  src/main/java/seedu/address/model/friend/gamefriendlink/GameFriendLink.java
  src/main/java/seedu/address/model/friend/gamefriendlink/UserName.java
  src/main/java/seedu/address/model/game/Game.java
  src/main/java/seedu/address/model/game/GameId.java
  src/main/java/seedu/address/model/game/GameIdContainsKeywordPredicate.java
  src/main/java/seedu/address/model/game/UniqueGamesList.java
  src/main/java/seedu/address/model/game/exceptions/DuplicateGameException.java
  src/main/java/seedu/address/model/game/exceptions/GameNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedFriend.java
  src/main/java/seedu/address/storage/JsonAdaptedGame.java
  src/main/java/seedu/address/ui/FriendCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditFriendDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/GetCommandTest.java
  src/test/java/seedu/address/logic/commands/LinkCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/friends/AddFriendCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/friends/AddFriendCommandTest.java
  src/test/java/seedu/address/logic/commands/friends/DeleteFriendCommandTest.java
  src/test/java/seedu/address/model/FriendsListTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/friend/FriendTest.java
  src/test/java/seedu/address/model/friend/UniqueFriendListTest.java
  src/test/java/seedu/address/model/game/GameTest.java
  src/test/java/seedu/address/storage/JsonAdaptedFriendTest.java
  src/test/java/seedu/address/testutil/EditFriendDescriptorBuilder.java
  src/test/java/seedu/address/testutil/FriendBuilder.java
  src/test/java/seedu/address/testutil/FriendUtil.java
  src/test/java/seedu/address/testutil/GameBuilder.java
  src/test/java/seedu/address/testutil/TypicalGames.java
Labels: enhancement

#71 Update link command
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/LinkCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/LinkCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/FriendsList.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/friend/Friend.java
  src/main/java/seedu/address/model/friend/UniqueFriendsList.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/LinkCommandTest.java
  src/test/java/seedu/address/logic/commands/friends/AddFriendCommandTest.java
  src/test/java/seedu/address/logic/commands/games/AddGameCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FriendsListParserTest.java
  src/test/java/seedu/address/logic/parser/LinkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: enhancement, hacktoberfest-accepted

#84 Refactor test stub and load storage file edge cases
  build.gradle
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/parser/friends/AddFriendCommandParser.java
  src/main/java/seedu/address/logic/parser/games/AddGameCommandParser.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/friends/AddFriendCommandTest.java
  src/test/java/seedu/address/logic/commands/games/AddGameCommandTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
Labels: enhancement

#92 Developer guide update for Storage component
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/address/storage/StorageManager.java
Labels: documentation, hacktoberfest-accepted

#102 Add add skill value to GameFriendLink functionality
  src/main/java/seedu/address/logic/commands/CommandType.java
  src/main/java/seedu/address/logic/commands/friends/AddFriendCommand.java
  src/main/java/seedu/address/logic/commands/friends/AddFriendGameSkillCommand.java
  src/main/java/seedu/address/logic/commands/friends/EditFriendCommand.java
  src/main/java/seedu/address/logic/commands/games/AddGameCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/friends/AddFriendGameSkillCommandParser.java
  src/main/java/seedu/address/logic/parser/friends/FriendCommandParser.java
  src/main/java/seedu/address/model/friend/Friend.java
  src/main/java/seedu/address/model/friend/exceptions/GameLinkNotFoundException.java
  src/main/java/seedu/address/model/gamefriendlink/GameFriendLink.java
  src/main/java/seedu/address/model/gamefriendlink/SkillValue.java
  src/main/java/seedu/address/storage/JsonAdaptedGameFriendLink.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/data/JsonSerializableFriendsListTest/typicalFriendsList.json
  src/test/java/seedu/address/logic/commands/friends/AddFriendCommandTest.java
  src/test/java/seedu/address/logic/commands/friends/AddFriendGameSkillCommandTest.java
  src/test/java/seedu/address/logic/commands/friends/EditFriendCommandTest.java
  src/test/java/seedu/address/logic/parser/friends/AddFriendGameSkillCommandParserTest.java
  src/test/java/seedu/address/logic/parser/friends/FriendCommandParserTest.java
  src/test/java/seedu/address/model/FriendsListTest.java
  src/test/java/seedu/address/model/friend/UniqueFriendsListTest.java
  src/test/java/seedu/address/model/gamefriendlink/GameFriendLinkTest.java
  src/test/java/seedu/address/model/gamefriendlink/SkillLevelTest.java
  src/test/java/seedu/address/model/gamefriendlink/UserNameTest.java
  src/test/java/seedu/address/storage/JsonAdaptedGameFriendLinkTest.java
  src/test/java/seedu/address/testutil/GameFriendLinkBuilder.java
  src/test/java/seedu/address/testutil/TypicalFriends.java
  src/test/java/seedu/address/testutil/TypicalGameFriendLinks.java
Labels: enhancement

#100 Add unlink functionality and refactor link command into friend package
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/CommandType.java
  src/main/java/seedu/address/logic/commands/friends/LinkFriendCommand.java
  src/main/java/seedu/address/logic/commands/friends/UnlinkFriendCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/MainParser.java
  src/main/java/seedu/address/logic/parser/friends/FriendCommandParser.java
  src/main/java/seedu/address/logic/parser/friends/LinkFriendCommandParser.java
  src/main/java/seedu/address/logic/parser/friends/UnlinkFriendCommandParser.java
  src/main/java/seedu/address/model/FriendsList.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/friend/Friend.java
  src/main/java/seedu/address/model/friend/UniqueFriendsList.java
  src/test/java/seedu/address/logic/commands/friends/LinkFriendCommandTest.java
  src/test/java/seedu/address/logic/commands/friends/UnlinkFriendCommandTest.java
  src/test/java/seedu/address/logic/parser/friends/LinkFriendCommandParserTest.java
  src/test/java/seedu/address/logic/parser/friends/UnlinkFriendCommandParserTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
Labels: enhancement, hacktoberfest-accepted

#103 Update 'Model' component in DG
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/team/yeluriketan.md
Labels: documentation, hacktoberfest-accepted
